name: C++ CI

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.10'  # Specify the CMake version you need

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev  # Install libpcap for your tests

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure  # Run tests using CTest, this will automatically run your test executables
